const LOCAL: Record<string, string> = {
  // Zone 1
  "Slime":                 "/monsters/slime.png",
  "Rat Swarm":             "/monsters/rat_swarm.png",
  "Goblin":                "/monsters/goblin.png",
  "Skeleton":              "/monsters/skeleton.png",
  "Forest Wolf":           "/monsters/wolf.png",
  "Zombie":                "/monsters/zombie.png",
  "Bandit":                "/monsters/bandit.png",
  "Wicked Witch":          "/monsters/witch.png",
  "Plague Rat":            "/monsters/plague_rat.png",
  "Stone Imp":             "/monsters/stone_imp.png",
  "Feral Hog":             "/monsters/feral_hog.png",
  "Cursed Scarecrow":      "/monsters/cursed_scarecrow.png",

  // Zone 2
  "Orc Brute":             "/monsters/orc.png",
  "Ghoul":                 "/monsters/ghoul.png",
  "Wraith":                "/monsters/wraith.png",
  "Vampire":               "/monsters/vampire.png",
  "Stone Golem":           "/monsters/stone_golem.png",
  "Dark Elf":              "/monsters/dark_elf.png",
  "Werewolf":              "/monsters/werewolf.png",
  "Cave Troll":            "/monsters/troll.png",
  "Bog Witch":             "/monsters/bog_witch.png",
  "Iron Golem":            "/monsters/iron_golem.png",
  "Shadow Rogue":          "/monsters/shadow_rogue.png",
  "Blood Wolf":            "/monsters/blood_wolf.png",

  // Zone 3
  "Demon":                 "/monsters/demon.png",
  "Dark Knight":           "/monsters/death_knight.png",
  "Hellhound":             "/monsters/hellhound.png",
  "Necromancer":           "/monsters/necromancer.png",
  "Shade":                 "/monsters/shadow.png",
  "Medusa":                "/monsters/medusa.png",
  "Death Knight":          "/monsters/death_knight.png",
  "Shadow Stalker":        "/monsters/shadow_rogue.png",
  "Plague Doctor":         "/monsters/plague_doctor.png",
  "Chaos Imp":             "/monsters/chaos_imp.png",
  "Bone Archer":           "/monsters/bone_archer.png",
  "Spectral Knight":       "/monsters/spectral_knight.png",

  // Zone 4
  "Dragon":                "/monsters/dragon.png",
  "Infernal Lord":         "/monsters/infernal_lord.png",
  "Chaos Beast":           "/monsters/chaos_imp.png",
  "Void Spawner":          "/monsters/void_entity.png",
  "Elder Demon":           "/monsters/demon.png",
  "Leviathan":             "/monsters/kraken.png",
  "Inferno Wyrm":          "/monsters/hell_wyrm.png",
  "Abyssal Specter":       "/monsters/abyssal_wraith.png",
  "Hell Wyrm":             "/monsters/hell_wyrm.png",
  "Magma Golem":           "/monsters/magma_golem.png",
  "Brimstone Fiend":       "/monsters/brimstone_fiend.png",
  "Abyssal Wraith":        "/monsters/abyssal_wraith.png",

  // Zone 5
  "Void Walker":           "/monsters/void_entity.png",
  "Cosmic Horror":         "/monsters/cosmic_horror.png",
  "Primordial Beast":      "/monsters/primordial_beast.png",
  "Abyss Titan":           "/monsters/void_titan.png",
  "Oblivion Drake":        "/monsters/dragon.png",
  "Null Entity":           "/monsters/void_entity.png",
  "Entropy Fiend":         "/monsters/null_demon.png",
  "Void Sovereign":        "/monsters/void_titan.png",
  "Phase Shifter":         "/monsters/phase_shifter.png",
  "Null Demon":            "/monsters/null_demon.png",
  "Starfire Drake":        "/monsters/starfire_drake.png",
  "Cosmic Abomination":    "/monsters/cosmic_abomination.png",

  // Zone 6
  "Corrupted Seraph":      "/monsters/seraph.png",
  "Fallen Angel":          "/monsters/fallen_angel.png",
  "Celestial Guardian":    "/monsters/seraph.png",
  "Light Wraith":          "/monsters/wraith.png",
  "Heaven's Exile":        "/monsters/fallen_angel.png",
  "Radiant Fiend":         "/monsters/luminous_fiend.png",
  "Astral Phantom":        "/monsters/spectral_knight.png",
  "Sanctified Horror":     "/monsters/cosmic_abomination.png",
  "Herald of Ruin":        "/monsters/herald_of_ruin.png",
  "Void Seraph":           "/monsters/void_seraph.png",
  "Luminous Fiend":        "/monsters/luminous_fiend.png",
  "Shattered Angel":       "/monsters/shattered_angel.png",

  // Zone 7
  "Kraken Spawn":          "/monsters/kraken.png",
  "Deep One":              "/monsters/abyssal.png",
  "Void Hydra":            "/monsters/void_entity.png",
  "Abyssal Revenant":      "/monsters/abyssal.png",
  "Nihil Serpent":         "/monsters/medusa.png",
  "Oblivion Husk":         "/monsters/skeleton.png",
  "Depth Walker":          "/monsters/abyssal_stalker.png",
  "Abyss Horror":          "/monsters/abyssal.png",
  "Trench Horror":         "/monsters/trench_horror.png",
  "Leviathan Spawn":       "/monsters/leviathan_spawn.png",
  "Void Parasite":         "/monsters/void_parasite.png",
  "Abyssal Stalker":       "/monsters/abyssal_stalker.png",

  // Zone 8
  "Reality Breach":        "/monsters/dimensional.png",
  "Chaos Lord":            "/monsters/infernal_lord.png",
  "Fractured Titan":       "/monsters/shattered_colossus.png",
  "Void Colossus":         "/monsters/void_titan.png",
  "Realm Stalker":         "/monsters/rift_stalker.png",
  "Dimensional Ripper":    "/monsters/dimensional.png",
  "Paradox Beast":         "/monsters/dimensional.png",
  "Entropy Avatar":        "/monsters/void_entity.png",
  "Rift Stalker":          "/monsters/rift_stalker.png",
  "Chaos Wraith":          "/monsters/chaos_wraith.png",
  "Shattered Colossus":    "/monsters/shattered_colossus.png",
  "Paradox Shade":         "/monsters/paradox_shade.png",

  // Zone 9
  "Eternal Sentinel":      "/monsters/eternal.png",
  "Time Ravager":          "/monsters/time_ravager.png",
  "Fate Weaver":           "/monsters/time_ravager.png",
  "Cosmic Predator":       "/monsters/cosmic_horror.png",
  "Soul Colossus":         "/monsters/void_titan.png",
  "Infinite Shade":        "/monsters/shadow.png",
  "Sanctum Guardian":      "/monsters/eternal.png",
  "Void Prophet":          "/monsters/the_eye.png",
  "Eternal Revenant":      "/monsters/eternal_revenant.png",
  "Temporal Fiend":        "/monsters/temporal_fiend.png",
  "Void Arbiter":          "/monsters/void_arbiter.png",
  "Sanctum Horror":        "/monsters/sanctum_horror.png",

  // Zone 10
  "Void God":              "/monsters/void_god.png",
  "Endless Horror":        "/monsters/endless_horror.png",
  "Null Titan":            "/monsters/null_titan.png",
  "Infinity Wraith":       "/monsters/infinity_wraith.png",
  "The Nameless":          "/monsters/the_nameless.png",
  "Oblivion God":          "/monsters/oblivion_god.png",
  "Eternal Devourer":      "/monsters/eternal_devourer.png",
  "Chaos Primordial":      "/monsters/chaos_primordial.png",
  "The Formless":          "/monsters/the_formless.png",
  "Primordial Shade":      "/monsters/primordial_shade.png",
  "Chaos Specter":         "/monsters/chaos_specter.png",
  "Infinite Abyss":        "/monsters/infinite_abyss.png",

  // Zone 11
  "Chaos Titan":           "/monsters/chaos_titan.png",
  "Primordial Revenant":   "/monsters/primordial_revenant.png",
  "Entropy Incarnate":     "/monsters/entropy_incarnate.png",
  "Void Annihilator":      "/monsters/void_annihilator.png",
  "Realm Destroyer":       "/monsters/realm_destroyer.png",
  "Time Annihilator":      "/monsters/time_annihilator.png",
  "Chaos Oracle":          "/monsters/chaos_oracle.png",
  "Primordial Fiend":      "/monsters/primordial_fiend.png",

  // Zone 12
  "Eternal Void":          "/monsters/eternal_void.png",
  "Dark Absolute":         "/monsters/dark_absolute.png",
  "The Primordial":        "/monsters/the_primordial.png",
  "Undying Chaos":         "/monsters/undying_chaos.png",
  "Void Absolute":         "/monsters/void_absolute.png",
  "Eternal Fiend":         "/monsters/eternal_fiend.png",
  "Dark Primordial":       "/monsters/dark_primordial.png",
  "The Nameless Void":     "/monsters/the_nameless_void.png",

  // Bosses
  "Bone Colossus":         "/monsters/bone_colossus.png",
  "Giant Forest Troll":    "/monsters/giant_forest_troll.png",
  "Ancient Barrow King":   "/monsters/ancient_barrow_king.png",
  "Ancient Wyrm":          "/monsters/ancient_wyrm.png",
  "Plague Harbinger":      "/monsters/plague_harbinger.png",
  "Deep Troll Shaman":     "/monsters/deep_troll_shaman.png",
  "Demon Overlord":        "/monsters/demon_overlord.png",
  "Shadow Titan":          "/monsters/shadow_titan.png",
  "Undead Lich":           "/monsters/undead_lich.png",
  "Plague Baron":          "/monsters/plague_baron.png",
  "Elder Dragon King":     "/monsters/elder_dragon_king.png",
  "Void Tyrant":           "/monsters/void_tyrant.png",
  "Abyssal Overlord":      "/monsters/abyssal_overlord.png",
  "Infernal Titan":        "/monsters/infernal_titan.png",
  "Cosmic Destroyer":      "/monsters/cosmic_destroyer.png",
  "Void Incarnate":        "/monsters/void_incarnate.png",
  "The Transcendent":      "/monsters/the_transcendent.png",
  "Entropy Lord":          "/monsters/entropy_lord.png",
  "Archangel of Ruin":     "/monsters/archangel_of_ruin.png",
  "Celestial Tyrant":      "/monsters/celestial_tyrant.png",
  "Celestial Annihilator": "/monsters/celestial_annihilator.png",
  "Abyss Leviathan":       "/monsters/abyss_leviathan.png",
  "The Depths Incarnate":  "/monsters/the_depths_incarnate.png",
  "Kraken Lord":           "/monsters/kraken_lord.png",
  "Reality Shatterer":     "/monsters/reality_shatterer.png",
  "Chaos Incarnate":       "/monsters/chaos_incarnate.png",
  "The Reality Eater":     "/monsters/the_reality_eater.png",
  "The Eternal":           "/monsters/the_eternal.png",
  "Fate's End":            "/monsters/fates_end.png",
  "The Undying":           "/monsters/the_undying.png",
  "The Void Absolute":     "/monsters/the_void_absolute.png",
  "Infinite Destroyer":    "/monsters/infinite_destroyer.png",
  "The Undying End":       "/monsters/the_undying_end.png",
  "Oblivion Incarnate":    "/monsters/oblivion_incarnate.png",
  "The Chaos Absolute":    "/monsters/the_chaos_absolute.png",
  "Primordial Annihilator":"/monsters/primordial_annihilator.png",
  "The Eternal End":       "/monsters/the_eternal_end.png",
  "Absolute Darkness":     "/monsters/absolute_darkness.png",
  "The Primordial Darkness":"/monsters/the_primordial_darkness.png",

  // Misc / pet sources
  "Lich":                  "/monsters/lich.png",
  "Plague":                "/monsters/plague.png",
  "Undying":               "/monsters/undying.png",
  "Eternal":               "/monsters/eternal.png",
  "Shadow":                "/monsters/shadow.png",
  "The Eye":               "/monsters/the_eye.png",
};

const FALLBACKS: [RegExp, string][] = [
  [/slime/i,                      "/monsters/slime.png"],
  [/rat|rodent/i,                 "/monsters/rat_swarm.png"],
  [/goblin/i,                     "/monsters/goblin.png"],
  [/skeleton|bone|barrow/i,       "/monsters/skeleton.png"],
  [/wolf|hound/i,                 "/monsters/wolf.png"],
  [/zombie/i,                     "/monsters/zombie.png"],
  [/bandit/i,                     "/monsters/bandit.png"],
  [/witch/i,                      "/monsters/witch.png"],
  [/orc/i,                        "/monsters/orc.png"],
  [/ghoul/i,                      "/monsters/ghoul.png"],
  [/vampire/i,                    "/monsters/vampire.png"],
  [/werewolf/i,                   "/monsters/werewolf.png"],
  [/troll/i,                      "/monsters/troll.png"],
  [/golem/i,                      "/monsters/stone_golem.png"],
  [/medusa/i,                     "/monsters/medusa.png"],
  [/lich/i,                       "/monsters/lich.png"],
  [/necromancer/i,                "/monsters/necromancer.png"],
  [/dragon|wyrm|drake/i,          "/monsters/dragon.png"],
  [/infernal/i,                   "/monsters/infernal_lord.png"],
  [/hellhound/i,                  "/monsters/hellhound.png"],
  [/demon|devil/i,                "/monsters/demon.png"],
  [/death.?knight/i,              "/monsters/death_knight.png"],
  [/knight|warrior/i,             "/monsters/spectral_knight.png"],
  [/kraken|squid|octopus/i,       "/monsters/kraken.png"],
  [/leviathan/i,                  "/monsters/abyss_leviathan.png"],
  [/seraph|angel/i,               "/monsters/seraph.png"],
  [/plague/i,                     "/monsters/plague.png"],
  [/wraith|specter|phantom/i,     "/monsters/wraith.png"],
  [/shade|shadow/i,               "/monsters/shadow.png"],
  [/cosmic|astral/i,              "/monsters/cosmic_horror.png"],
  [/primordial|ancient/i,         "/monsters/primordial_beast.png"],
  [/void/i,                       "/monsters/void_entity.png"],
  [/null/i,                       "/monsters/null_demon.png"],
  [/abyss|abyssal/i,              "/monsters/abyssal.png"],
  [/chaos/i,                      "/monsters/chaos_imp.png"],
  [/entropy/i,                    "/monsters/null_demon.png"],
  [/titan|colossus/i,             "/monsters/void_titan.png"],
  [/rift|dimensional|paradox/i,   "/monsters/dimensional.png"],
  [/eternal|undying/i,            "/monsters/eternal.png"],
  [/time|temporal|chrono/i,       "/monsters/time_ravager.png"],
  [/blood/i,                      "/monsters/blood_wolf.png"],
  [/magma|fire|inferno|brimstone/i,"/monsters/magma_golem.png"],
  [/stalker|rogue/i,              "/monsters/shadow_rogue.png"],
  [/horror|formless/i,            "/monsters/endless_horror.png"],
];

export function getMonsterImage(name: string): string {
  if (LOCAL[name]) return LOCAL[name];
  const lower = name.toLowerCase();
  for (const [rx, path] of FALLBACKS) {
    if (rx.test(lower)) return path;
  }
  return "/monsters/void_entity.png";
}
